#!/usr/bin/env bash
# Build BetterExperience for Corrupted Modeling Agency (IL2CPP) and deploy it.
#
# SEPARATE FROM deploy.sh ON PURPOSE. That script builds the Mono/net472 mod for SMA and deploys
# to two installs; this one builds net6/IL2CPP for a third. Sharing them would mean one command
# that half-succeeds when a target is missing, which is precisely the class of silent staleness
# deploy.sh exists to prevent.
#
#   ./build-cma.sh          build + deploy
#   ./build-cma.sh -n       build only
set -u

CMA="G:/Games/AAA/Corrupted Modeling Agency 0.61"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="F:/Games/AAA/SMA_23.1_HomeworkTestbed/_build/BetterExperience.CMA/Release"
DEST="$CMA/BepInEx/plugins/BetterExperience"
DEPLOY=1
[ "${1:-}" = "-n" ] && DEPLOY=0

# The interop assemblies are GENERATED by BepInEx 6 on first run. Without them every game type is
# unresolvable and the build fails in hundreds of confusing ways, so say the real reason up front.
if [ ! -d "$CMA/BepInEx/interop" ] || [ -z "$(ls "$CMA/BepInEx/interop"/*.dll 2>/dev/null)" ]; then
  echo "!!! No interop assemblies at $CMA/BepInEx/interop"
  echo "    Launch the game once with BepInEx 6 installed and let it reach the menu."
  exit 1
fi
echo "interop: $(ls "$CMA/BepInEx/interop"/*.dll | wc -l) assemblies"

export MSBUILDDISABLENODEREUSE=1
echo "=== building (net6.0 / IL2CPP) ==="
dotnet build "$HERE/BetterExperience.CMA.csproj" -c Release --nologo -nodeReuse:false 2>&1 \
  | grep -iE "error|warning CS[0-9]+:|Build succeeded" | head -25

DLL="$OUT/BetterExperience.dll"
[ -f "$DLL" ] || { echo "!!! BUILD PRODUCED NO DLL"; exit 1; }

if [ "$DEPLOY" -eq 1 ]; then
  mkdir -p "$DEST"
  cp -f "$DLL" "$DEST/BetterExperience.dll" || { echo "!!! copy failed (game running?)"; exit 1; }
  [ -f "${DLL%.dll}.pdb" ] && cp -f "${DLL%.dll}.pdb" "$DEST/"
  # Byte-verify, same discipline as the SMA deploy: a stale DLL is worse than a failed build
  # because it silently invalidates the next round of testing.
  if cmp -s "$DLL" "$DEST/BetterExperience.dll"; then
    echo "deployed + verified -> $DEST"
  else
    echo "!!!! STALE: $DEST/BetterExperience.dll does not match the build"; exit 1
  fi
fi
